/****** Object:  Table [dbo].[RecordIdentifier]    Script Date: 02/16/2017 12:28:21 ******/
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (10, N'Header')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (11, N'Street Record')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (12, N'Street Cross Reference')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (13, N'Elementary Street Unit')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (14, N'ESU Co-ordinate')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (15, N'Street Descriptor')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (21, N'Basic Land and Property Unit')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (22, N'Provenance')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (23, N'Application Cross Reference')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (24, N'Land and Property Identifier')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (25, N'BLPU Extent')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (26, N'BLPU Extent Polygon')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (27, N'BLPU Extent Polygon Vertex')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (29, N'LLPG Metadata')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (98, N'Key Sequence')
INSERT [dbo].[RecordIdentifier] ([RecordIdentifierId], [Description]) VALUES (99, N'Trailer')
